### ISSUE TITLE
Professional Information

### ISSUE THREAD

**Issue by MohammadIqbalHussain** [Appkube-hrms/appkube-hrms-ui#28]
Directly clicking on Next button with out filling a professional detail form
Alert is displaying
As well as navigating to next page
![Screenshot 2024-04-01 143201](https://github.com/Appkube-hrms/appkube-hrms-ui/assets/156897342/1b872414-e548-4edd-8845-5ffe1bc5ab61)
Navigates to equipment details
![Screenshot 2024-04-01 144244](https://github.com/Appkube-hrms/appkube-hrms-ui/assets/156897342/0206b8f2-ac9b-4974-a797-c853dbc060bb)

**Comment by syedsmuzakkir** [comment]
Issue Resolved

**Comment by mohammedsohailz** [comment]
@syedsmuzakkir still this bug is not solved!

**Comment by syedsmuzakkir** [comment]
already resolved updated code is on the https://eip.synectiks.net 

navigating to another page is used for testing purpose if you want me to disable that tab navigation please let me know?
